version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server.nginx
    image: server.nginx
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./certs:/certs
      - ./www:/www
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d
    networks:
      - outside
networks:
  outside:
    external:
      name: nginx_proxy_reverse
